defaults: &defaults
  adapter: mysql2
  username: root
  password:
  encoding: utf8
  host: 127.0.0.1
  reconnect: true

development:
  <<: *defaults
  database: quiz_station_development

staging:
  <<: *defaults
  database: quiz_station_staging

production:
  <<: *defaults
  database: quiz_station_production

test:
  <<: *defaults
  database: quiz_station_test
